language: node_js
node_js:
  - "node"

script:
  - npm install
  - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
