language: node_js
node_js:
  - "node"

before_script:
  - sed -i 's/"version": "\([0-9]\+\.[0-9]\+\.\)[0-9]\+",/"version": "\1'"$TRAVIS_BUILD_NUMBER"'",/' app/manifest.json

script:
  - npm install
  - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
