language: node_js
node_js:
  - "node"

before_script:
  - ./scripts/before_script.sh

script:
  - npm install
  - npm run build

cache:
  directories:
    - "node_modules"

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
